apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-deployment
  labels:
    app: cache-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache-app
  template:
    metadata:
      labels:
        app: cache-app
    spec:
      containers:
        - name: cache-app
          image: georgeabot/cache-microservice:1.0.0
          ports:
            - containerPort: 4040
          env:
            - name: MONGODB_CONNECTION_STRING
              valueFrom:
                configMapKeyRef:
                  name: tequila-configmap
                  key: database_url
        
---
apiVersion: v1
kind: Service
metadata:
  name: cache-service
spec:
  selector:
    app: cache-app
  ports:
  - protocol: TCP
    port: 4040
    targetPort: 4040
  
