apiVersion: v1
kind: ConfigMap
metadata:
  name: tequila-configmap
data:
  database_url: mongodb://mongodb-service:27017/FlightDB
  tequila_url: http://tequila-service:3000/api/v1/flight
  view_url: http://cache-service:4040/api/v1/flights
  