apiVersion: apps/v1
kind: Deployment
metadata:
  name: view-deployment
  labels:
    app: kata-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: view-app
  template:
    metadata:
      labels:
        app: view-app
    spec:
      containers:
        - name: view-app
          image: georgeabot/view-app:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: VIEW_FLIGHTS_URL
              valueFrom:
                configMapKeyRef:
                  name: tequila-configmap
                  key: view_url
---
apiVersion: v1
kind: Service
metadata:
  name: view-service
spec:
  type: NodePort
  selector:
    app: view-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  
